language: php

php:
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql
  - postgresql

env:
  - DB=mysql RUNLEVEL=0
  - DB=mysql RUNLEVEL=10
  - DB=pgsql RUNLEVEL=0
  - DB=pgsql RUNLEVEL=10

before_script:
  - composer selfupdate --no-progress
  - travis_retry composer install --prefer-dist
  - mkdir tests/_temp
  - "sh -c \"if [ '$DB' = 'mysql' ]; then cp tests/_helpers/mysql.neon tests/tests.local.neon; fi\""
  - "sh -c \"if [ '$DB' = 'pgsql' ]; then cp tests/_helpers/pgsql.neon tests/tests.local.neon; fi\""

script:
  - src/run-tests --bootstrap tests/bootstrap.php
  - php tests/Scaffold/GenerateStructure.php
  - cp tests/FakeBootstrapForScaffold.php tests/_temp/scaffold/bootstrap.php
  - php tests/_temp/scaffold/PresenterPresenter.phpt
  - php tests/_temp/scaffold/ModuleModule/PresenterPresenter.phpt

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

notifications:
  email: false
